export const payType = [
  { 'key': '1', 'value': '公司帐号' },
  { 'key': '2', 'value': '农业银行' },
  { 'key': '3', 'value': '建设银行' },
  { 'key': '4', 'value': '工商银行' },
  { 'key': '5', 'value': '交通银行' },
  { 'key': '6', 'value': '支付宝对私' },
  { 'key': '7', 'value': '招商银行' },
  { 'key': '8', 'value': ' 现金支付' },
  { 'key': '9', 'value': '中国银行' },
  { 'key': '10', 'value': '邮政汇款' },
  { 'key': '11', 'value': '转账支票' },
  { 'key': '12', 'value': '民生银行' },
  { 'key': '13', 'value': '平安银行 ' },
  { 'key': '14', 'value': '联合银行' },
  { 'key': '15', 'value': '公司帐号私对公' },
  { 'key': '16', 'value': '公司帐号公对公' },
  { 'key': '17', 'value': 'POS机刷卡' },
  { 'key': '18', 'value': '微信支付' },
  { 'key': '19', 'value': '公司支付宝' },
  { 'key': '20', 'value': '缴现金' },
  { 'key': '21', 'value': '公司账2375私对公' },
  { 'key': '22', 'value': '公司账2375公对公' },
  { 'key': '23', 'value': '公司账7997私对公' },
  { 'key': '24', 'value': '公司账7997公对公' },
  { 'key': '25', 'value': '公司帐农行' },
  { 'key': '26', 'value': '公司账POSS机' },
  { 'key': '27', 'value': '公司账招行公对公' },
  { 'key': '28', 'value': '公司账招行私对公' },
  { 'key': '29', 'value': '公司账招行' }
]
export const resultType = [
  { 'key': '1', 'value': '密码正确' },
  { 'key': '2', 'value': '密码错误' }
]
